# generated by django 6.0.8 on 2026-10-07 14:55

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


SIGNS = [
    ("Aries", "aries", "fire", "cardinal"),
    ("Taurus", "taurus", "earth", "fixed"),
    ("Gemini", "gemini", "air", "mutable"),
    ("Cancer", "cancer", "water", "cardinal"),
    ("Leo", "leo", "fire", "fixed"),
    ("Virgo", "virgo", "earth", "mutable"),
    ("Libra", "libra", "air", "cardinal"),
    ("Scorpio", "scorpio", "water", "fixed"),
    ("Sagittarius", "sagittarius", "fire", "mutable"),
    ("Capricorn", "capricorn", "earth", "cardinal"),
    ("Aquarius", "aquarius", "air", "fixed"),
    ("Pisces", "pisces", "water", "mutable"),
]

PLANETS = [
    ("Sun", "☉"),
    ("Moon", "☽"),
    ("Mercury", "☿"),
    ("Venus", "♀"),
    ("Mars", "♂"),
    ("Jupiter", "♃"),
    ("Saturn", "♄"),
]

RULERS = {
    "Aries": "Mars",
    "Taurus": "Venus",
    "Gemini": "Mercury",
    "Cancer": "Moon",
    "Leo": "Sun",
    "Virgo": "Mercury",
    "Libra": "Venus",
    "Scorpio": "Mars",
    "Sagittarius": "Jupiter",
    "Capricorn": "Saturn",
    "Aquarius": "Saturn",
    "Pisces": "Jupiter",
}

EXALTATIONS = {
    "Sun": "Aries",
    "Moon": "Taurus",
    "Mercury": "Virgo",
    "Venus": "Pisces",
    "Mars": "Capricorn",
    "Jupiter": "Cancer",
    "Saturn": "Libra",
}


def seed_zodiac_data(apps, schema_editor):
    Planet = apps.get_model("astrology", "Planet")
    PlanetSignDignity = apps.get_model("astrology", "PlanetSignDignity")
    PlanetaryRulership = apps.get_model("astrology", "PlanetaryRulership")
    ZodiacSign = apps.get_model("astrology", "ZodiacSign")

    # numbered rows use the same Aries-to-Pisces order as chart calculations,
    # so later sign comparisons can use a stable circular position.
    signs = {}
    for position, (name, slug, element, modality) in enumerate(SIGNS, start=1):
        signs[name] = ZodiacSign.objects.create(
            name=name,
            slug=slug,
            position=position,
            element=element,
            modality=modality,
        )

    planets = {
        name: Planet.objects.create(name=name, symbol=symbol)
        for name, symbol in PLANETS
    }
    for sign_name, planet_name in RULERS.items():
        PlanetaryRulership.objects.create(
            planet=planets[planet_name],
            sign=signs[sign_name],
        )

    # adding six positions modulo twelve gives each sign its exact opposite
    # while keeping this reference table compact and deterministic.
    opposite_signs = {
        name: SIGNS[(position + 6) % 12][0]
        for position, (name, _slug, _element, _modality) in enumerate(SIGNS)
    }
    # deriving domicile and detriment maps from rulership data avoids a second
    # manually maintained list that could disagree with the ruler records.
    domiciles = {
        planet_name: {
            sign_name
            for sign_name, ruler in RULERS.items()
            if ruler == planet_name
        }
        for planet_name, _symbol in PLANETS
    }
    debilitations = {
        planet_name: opposite_signs[sign_name]
        for planet_name, sign_name in EXALTATIONS.items()
    }
    detriments = {
        planet_name: {
            opposite_signs[sign_name]
            for sign_name in domiciles[planet_name]
        }
        for planet_name, _symbol in PLANETS
    }

    # generate the full seven-by-twelve matrix once and bulk insert it, making
    # every planet/sign lookup complete with a single indexed database query.
    conditions = []
    for planet_name, _symbol in PLANETS:
        for sign_name, _slug, _element, _modality in SIGNS:
            if EXALTATIONS[planet_name] == sign_name:
                condition = "exalted"
            elif debilitations[planet_name] == sign_name:
                condition = "debilitated"
            elif sign_name in domiciles[planet_name]:
                condition = "dignified"
            elif sign_name in detriments[planet_name]:
                condition = "undignified"
            else:
                condition = "neutral"
            conditions.append(
                PlanetSignDignity(
                    planet=planets[planet_name],
                    sign=signs[sign_name],
                    condition=condition,
                )
            )
    PlanetSignDignity.objects.bulk_create(conditions)


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0001_savedchart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('browser_token_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ZodiacSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('position', models.PositiveSmallIntegerField(unique=True)),
                ('element', models.CharField(max_length=10)),
                ('modality', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='BirthChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField()),
                ('chart_context', models.JSONField()),
                ('placements', models.JSONField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=300, null=True)),
                ('location_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('birth_timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('has_birth_time', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_charts', to='astrology.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanetSignDignity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('exalted', 'Exalted'), ('dignified', 'Dignified'), ('neutral', 'Neutral'), ('undignified', 'Undignified'), ('debilitated', 'Debilitated')], max_length=12)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_conditions', to='astrology.planet')),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet_conditions', to='astrology.zodiacsign')),
            ],
        ),
        migrations.CreateModel(
            name='PlanetaryRulership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulerships', to='astrology.planet')),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulers', to='astrology.zodiacsign')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=9)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birth_chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='astrology.birthchart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='astrology.user')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['user', 'birth_chart', 'created_at'], name='astrology_c_user_id_a24236_idx')],
            },
        ),
        migrations.CreateModel(
            name='BirthChartSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_key', models.CharField(max_length=40)),
                ('summary_data', models.JSONField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='astrology.birthchart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_summaries', to='astrology.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'placement_key'], name='astrology_b_user_id_65fd7c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('birth_chart__isnull', False)), fields=('birth_chart', 'placement_key'), name='unique_chart_placement_summary')],
            },
        ),
        migrations.AddIndex(
            model_name='birthchart',
            index=django.contrib.postgres.indexes.GinIndex(fields=['form_data'], name='birthchart_form_data_gin'),
        ),
        migrations.AddConstraint(
            model_name='planetsigndignity',
            constraint=models.UniqueConstraint(fields=('planet', 'sign'), name='unique_planet_sign_dignity'),
        ),
        migrations.AddConstraint(
            model_name='planetaryrulership',
            constraint=models.UniqueConstraint(fields=('planet', 'sign'), name='unique_planetary_rulership'),
        ),
        migrations.AddConstraint(
            model_name='planetaryrulership',
            constraint=models.UniqueConstraint(fields=('sign',), name='unique_zodiac_sign_ruler'),
        ),
        # seeding reference rows with the schema keeps new databases ready for
        # chart calculations immediately after the migration completes.
        migrations.RunPython(seed_zodiac_data, migrations.RunPython.noop),
    ]
