# generated by django 6.0.8 on 2026-10-07 15:12

from django.db import migrations, models


HOUSE_AREAS = [
    ("First House", ["self", "body", "approach"]),
    ("Second House", ["resources", "family", "speech"]),
    ("Third House", ["effort", "skills", "siblings"]),
    ("Fourth House", ["home", "roots", "foundations"]),
    ("Fifth House", ["learning", "creativity", "children"]),
    ("Sixth House", ["work", "service", "health"]),
    ("Seventh House", ["partnerships", "agreements"]),
    ("Eighth House", ["shared resources", "transformation"]),
    ("Ninth House", ["teachers", "beliefs", "long journeys"]),
    ("Tenth House", ["work", "responsibility", "public role"]),
    ("Eleventh House", ["friends", "networks", "gains"]),
    ("Twelfth House", ["rest", "retreat", "release"]),
]


def seed_house_areas(apps, schema_editor):
    # use migration-local models and one bulk insert so later model edits
    # cannot change this historical seed and setup requires only one round trip.
    House = apps.get_model("astrology", "House")
    House.objects.bulk_create([
        House(number=number, name=name, representations=areas)
        for number, (name, areas) in enumerate(HOUSE_AREAS, start=1)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0002_planet_user_zodiacsign_birthchart_planetsigndignity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('representations', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.RunPython(seed_house_areas, migrations.RunPython.noop),
    ]
