# generated by Django 6.0.8 on 2026-10-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0003_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthchart',
            name='ayanamsa',
            field=models.CharField(blank=True, choices=[('lahiri', 'Lahiri/Chitrapaksha')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='birthchart',
            name='house_system',
            field=models.CharField(choices=[('whole_sign', 'Whole sign'), ('placidus', 'Placidus')], default='whole_sign', max_length=12),
        ),
        migrations.AddField(
            model_name='birthchart',
            name='zodiac_system',
            field=models.CharField(choices=[('tropical', 'Tropical'), ('sidereal', 'Sidereal')], default='tropical', max_length=8),
        ),
    ]
